version: '3.8'

services:
  nginx:
    container_name: nginx_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8201:80"
    volumes:
      - ./app:/usr/share/nginx/html

